### Day 2

* https://peps.python.org/pep-0008/#naming-conventions
* diverse code formatter, linter, newest tool (fast): https://github.com/astral-sh/ruff


Recap:

* int, float, str, bool
* list, tuple, dict, set
* builtin: len, min, max, sorted, int, str, float, bool, sum, range, map, print, local, input, round, slice, type, complex, hex, oct, bin, format, list, set, dict, help, reverse, tuple
* dynamic typing, duck typing, first class functions
* for V in CONTAINER, while CONDITION, "if COND else ..."

Today:

* function
* classes, OO
* exception handling

Other:

* stdlib, serialization, json, xml
* pandas
* project structure
* data model, generators, decorators, ...

Keywords: https://docs.python.org/3/reference/lexical_analysis.html#keywords

```
False      await      else       import     pass
None       break      except     in         raise
True       class      finally    is         return
and        continue   for        lambda     try
as         def        from       nonlocal   while
assert     del        global     not        with
async      elif       if         or         yield
```

### Functions



In [6]:
def f():
    pass

In [7]:
type(f)

function

In [10]:
result = f()

In [13]:
print(result)

None


In [18]:
def f(a):
    return 2 * a

In [22]:
f(2.0)

4.0

In [23]:
def f(a, b, c):
    return a + b + c

In [24]:
f(1, 2, 3)

6

In [31]:
def f(*args):
    """ sums all arguments, args is a tuple """
    print(f"got {len(args)}")
    return sum(args)

In [36]:
f(1.0, 2, 3)

<class 'tuple'>
got 3


6.0

In [49]:
def f(a):
    # if type(a) != int: # ininstance(obj, type)
    if not isinstance(a, int):
        raise ValueError("works of numbers only")
    else:
        return 3 * a

In [51]:
f(123)

369

Keywords arguments

In [54]:
def f(name="world"):
    print(f"hello {name}")

In [59]:
f(name="dresden")

hello dresden


In [66]:
def f(greeting, name="martin"):
    return f"{greeting} {name}!"

In [67]:
f("hey", name="world")

'hey world!'

In [68]:
def f(**kwargs):
    print(kwargs)

In [72]:
def g(*args, **kwargs):
    print(args)
    print(kwargs)

In [74]:
g(1, 2, name="martin")

(1, 2)
{'name': 'martin'}


In [76]:
def f(vs, outfile=None):
    print(vs)
    if outfile:
        with open(outfile, "w") as f:
            f.write("".join(numbers))

In [79]:
f(["a", "b", "c"])

['a', 'b', 'c']


In [80]:
f(["a", "b", "c"])

['a', 'b', 'c']


In [84]:
f(["a", "b", "c"], outfile="g.txt")

['a', 'b', 'c']


In [85]:
def g(*args, **kwargs):
    print(args)
    print(kwargs)

In [87]:
def f(a, b):
    return (2 * a, 3 * b)

In [90]:
x, y = f(1, 2) # tuple unpacking

In [91]:
def f():
    def g():
        return "hello from g"
    return g

In [93]:
x = f()

In [94]:
type(x)

function

In [95]:
x()

'hello from g'

In [100]:
def make_adder(n):
    # closure
    def add(a):
        return n + a
    return add

In [101]:
add10 = make_adder(10)

In [102]:
add10(3)

13

In [103]:
add

NameError: name 'add' is not defined

Example for "decorator" using "closures":

```python
from numba import njit
import random

@njit
def monte_carlo_pi(nsamples):
    acc = 0
    for i in range(nsamples):
        x = random.random()
        y = random.random()
        if (x ** 2 + y ** 2) < 1.0:
            acc += 1
    return 4.0 * acc / nsamples
```

----

```python
from flask import Flask

app = Flask(__name__)

@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>"
```

In [105]:
list(map(lambda x: 2 * x, [1, 2, 3]))

[2, 4, 6]

In [106]:
list(map(add10, [1, 2, 3]))

[11, 12, 13]

In [107]:
def f(a, b, c):
    """
    This function sums the three numbers given.
    """
    return a + b + c


In [108]:
f(1, 2, 3)

6

In [109]:
help(f)

Help on function f in module __main__:

f(a, b, c)
    This function sums the three numbers given.



#### classes and object

In [111]:
def _my_private_func():
    print("hello")

In [112]:
_my_private_func()

hello


In [113]:
class FirstClass:
    pass

In [116]:
class A:
    pass

In [117]:
type(A)

type

In [118]:
a = A()

In [119]:
type(a)

__main__.A

In [37]:
class Person:
    def __init__(self, name, city):
        self.name = name
        self.city = city
        self._something_private = "private"
    
    def greet(self):
        print(f"hello {self.name} from {self.city}")

    def move_to_city(self, other_city):
        self.city = other_city


In [38]:
martin = Person("martin", "leipzig")

In [39]:
martin.greet()

hello martin from leipzig


In [41]:
martin.move_to_city("dresden")
martin.greet()

hello martin from dresden


In [35]:
thomas = Person("thomas", "dresden")

In [36]:
thomas.greet()

hello thomas from dresden


In [42]:
import requests

In [43]:
req = requests.Request()

In [81]:
class Person:
    def __init__(self, name, city):
        self.name = name
        self.city = city
        self._something_private = "private"
    
    def greet(self):
        print(f"hello {self.name} from {self.city}")

    def move_to_city(self, other_city):
        self.city = other_city

    def greet_from_city(self, other_city):
        self.move_to_city(other_city)
        self.greet()

    @staticmethod
    def is_a_cat():
        return False
    
    def __str__(self):
        return f'Object person with name {self.name} from {self.city}'
    
    def __repr__(self):
        return self.__str__()
    

In [82]:
martin = Person("martin", "leipzig")

In [91]:
print(martin)

Object person with name martin from leipzig


In [69]:
martin.is_a_cat()

False

In [52]:
martin.greet_from_city("dresden")

hello martin from dresden


In [88]:
dd = {"a": 1, "b": 2}

In [89]:
dd

{'a': 1, 'b': 2}

In [92]:
class A:
    def m(self):
        print("hello from A")

In [101]:
class B(A):
    def m(self):
        super().m()
        print("hello from B")

In [102]:
b = B()

In [103]:
b.m()

hello from A
hello from B


In [141]:
class A:
    def m(self):
        print("hello from A")

class B(A):
    def m(self):
        print("hello from B")

class C(A):
    def m(self):
        print("hello from C")

class D(C, B):
    def m(self):
        super().m()
        print("hello from D")

In [142]:
d = D()

In [143]:
d.m()

hello from C
hello from D


In [144]:
D.__mro__

(__main__.D, __main__.C, __main__.B, __main__.A, object)

In [146]:
class Person:
    def __init__(self, name, city):
        self.name = name
        self.city = city
        self._something_private = "private"
    
    def greet(self):
        print(f"hello {self.name} from {self.city}")

    def move_to_city(self, other_city):
        self._take_a_train()
        self.city = other_city

    def _take_a_train(self):
        print("taking a train ...")

    def greet_from_city(self, other_city):
        self.move_to_city(other_city)
        self.greet()

    @staticmethod
    def is_a_cat():
        return False
    
    def __str__(self):
        return f'Object person with name {self.name} from {self.city}'
    
    def __repr__(self):
        return self.__str__()

In [148]:
dd = dict({"a": 1, "b" : 2})

In [149]:
dd??

Type:        dict
String form: {'a': 1, 'b': 2}
Length:      2
Docstring:  
dict() -> new empty dictionary
dict(mapping) -> new dictionary initialized from a mapping object's
    (key, value) pairs
dict(iterable) -> new dictionary initialized as if via:
    d = {}
    for k, v in iterable:
        d[k] = v
dict(**kwargs) -> new dictionary initialized with the name=value pairs
    in the keyword argument list.  For example:  dict(one=1, two=2)

In [161]:

class MyStr(str):
    def __eq__(self, other):
        return self.lower() == other.lower()

In [162]:
s = MyStr("hello")

In [163]:
t = MyStr("HELLO")

In [164]:
s == t

True

In [165]:
class LoggedDict(dict):
    def __setitem__(self, key, value):
        print(f"setting {key} on dictionary to {value}")
        super().__setitem__(key, value)

In [166]:
dd = LoggedDict()

In [167]:
dd["name"] = "martin"

setting name on dictionary to martin


In [186]:
class Series:

    def __init__(self, *values):
        """ Create Series from list of numbers. """
        if len(values) == 0:
            self.data = []
        elif isinstance(values[0], list):
            self.data = values[0] 
        else:
            self.data = list(values)
    
    def max(self):
        return max(self.data)
    
    def min(self):
        return min(self.data)
    
    def avg(self):
        if len(self.data) == 0:
            raise ValueError("no data")
        return sum(self.data) / len(self.data)
    

In [190]:
s = Series(1, 2, 3)

In [191]:
s.min()

1

In [192]:
s.avg()

2.0

### Exception 

* https://docs.python.org/3/library/exceptions.html#exception-hierarchy

In [194]:
1 / 0

ZeroDivisionError: division by zero

In [227]:
import random
aList = [1, 2, 3]
try:
    if random.random() > 0.5:
        1 / 0
    aList[4]
except ZeroDivisionError as exc:
    print(f"caught exception: {exc} of type {type(exc)}")
except IndexError:
    print("index error") # log to file ...
    raise

index error


IndexError: list index out of range

In [222]:
def avg(iterable):
    if len(iterable) == 0:
        raise ValueError("cannot be empty")
    return sum(iterable) / len(iterable)

In [214]:
avg([])

ValueError: cannot be empty

### Basic IO

In [229]:
f = open("dummy.txt", "w")

In [230]:
type(f)

_io.TextIOWrapper

In [232]:
f.write("hello world!\n")

13

In [236]:
f.close()

In [238]:
f = open("dummy.txt")

In [243]:
f.seek(0)

0

In [246]:
f.read()

''

In [247]:
f.close()

In [250]:
with open("dummy.txt") as f: # context manager
    print(f.read())

f.closed

hello world!



True

In [253]:
with open("numbers.txt") as f:
    for line in f:
        print(line.strip())

1
2
3
4
5
6
7
8


In [254]:
import json

In [265]:
data = {
    "city": "dresden",
    "year": 2024,
    "lines": [1, 2, 3],
}

In [266]:
json.dumps(data)

'{"city": "dresden", "year": 2024, "lines": [1, 2, 3]}'

In [267]:
with open("data.json", "w") as f:
    f.write(json.dumps(data))

In [268]:
with open("data.json", "w") as f:
    json.dump(data, f)

In [270]:
with open("data.json") as f:
    my_data = json.load(f)

In [271]:
my_data

{'city': 'dresden', 'year': 2024, 'lines': [1, 2, 3]}

In [272]:
!pip install requests

In [273]:
import requests

In [281]:
requests.__file__

'/home/tir/code/miku/pythonpath/.venv/lib/python3.8/site-packages/requests/__init__.py'

In [275]:
resp = requests.get("https://api.blockchain.com/v3/exchange/tickers")

In [278]:
ticker = resp.json()

In [280]:
len(ticker)

162

In [282]:
import os

In [283]:
os.path.exists("/tmp")

True

In [285]:
import glob

In [291]:
glob.glob("*.*")

['stdinread.py',
 'user_input.py',
 'dummy.txt',
 'chatbot.py',
 'crash.py',
 'numbers.txt',
 'g.txt',
 'sample.ipynb',
 'day2.ipynb',
 'hello.ipynb',
 'garbled.py',
 'data.json',
 'f.txt']

In [297]:
for root, dir, files in os.walk("."):
    for file in files:
        print(os.path.join(root, file))

./stdinread.py
./user_input.py
./dummy.txt
./chatbot.py
./crash.py
./numbers.txt
./g.txt
./sample.ipynb
./day2.ipynb
./hello.ipynb
./garbled.py
./data.json
./f.txt
./.ipynb_checkpoints/hello-checkpoint.ipynb


In [298]:
data = """<?xml version="1.0"?>
<data>
    <country name="Liechtenstein">
        <rank>1</rank>
        <year>2008</year>
        <gdppc>141100</gdppc>
        <neighbor name="Austria" direction="E"/>
        <neighbor name="Switzerland" direction="W"/>
    </country>
    <country name="Singapore">
        <rank>4</rank>
        <year>2011</year>
        <gdppc>59900</gdppc>
        <neighbor name="Malaysia" direction="N"/>
    </country>
    <country name="Panama">
        <rank>68</rank>
        <year>2011</year>
        <gdppc>13600</gdppc>
        <neighbor name="Costa Rica" direction="W"/>
        <neighbor name="Colombia" direction="E"/>
    </country>
</data>
"""

In [299]:
import xml.etree.ElementTree as ET
root = ET.fromstring(data)

for child in root:
    print(child.tag, child.attrib)

root[0][1].text

country {'name': 'Liechtenstein'}
country {'name': 'Singapore'}
country {'name': 'Panama'}


'2008'

In [300]:
### numpy

In [1]:
!pip install numpy

In [2]:
import numpy as np # import "alias"

In [9]:
a = np.array([1, 2, 3])

In [10]:
a

array([1, 2, 3])

In [11]:
a.shape

(3,)

In [12]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [13]:
np.ones((2, 3, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [14]:
np.random.random((10, 10))

array([[0.57098405, 0.3299676 , 0.16772044, 0.8359027 , 0.06683579,
        0.05252536, 0.81932824, 0.51625643, 0.83534416, 0.67792804],
       [0.70440897, 0.36714926, 0.87206622, 0.62387016, 0.70206786,
        0.77299431, 0.77762257, 0.05418685, 0.17833122, 0.50022767],
       [0.02128695, 0.27088435, 0.6568902 , 0.66251399, 0.68158453,
        0.19539855, 0.08882588, 0.55512604, 0.48291942, 0.17667096],
       [0.03106633, 0.65963404, 0.45471442, 0.77218073, 0.07721795,
        0.63388217, 0.71526789, 0.76297388, 0.83023207, 0.78060328],
       [0.08323111, 0.11850596, 0.30546143, 0.38162838, 0.46592667,
        0.71007385, 0.51161152, 0.89407433, 0.25761235, 0.90264355],
       [0.61062837, 0.49417918, 0.26301624, 0.87732089, 0.05512715,
        0.21115749, 0.15868975, 0.13589905, 0.34230455, 0.0128009 ],
       [0.13046893, 0.92738827, 0.82781398, 0.4993096 , 0.4751266 ,
        0.14081108, 0.09148524, 0.88705032, 0.49754184, 0.83946414],
       [0.84454833, 0.65264816, 0.2036338